#!/bin/bash
set -euo pipefail

# Quality-assess lopezdp_utils modules against López de Prado theory and apply fixes
# Generated by create-headless-workflow skill

PROJECT_PATH="$(cd "$(dirname "$0")/.." && pwd)"
LOG_FILE="$PROJECT_PATH/qa-audit-log.md"
LOCK_FILE="/tmp/qa-audit.lock"

# Prevent concurrent runs
if [ -f "$LOCK_FILE" ]; then
    PID=$(cat "$LOCK_FILE")
    if kill -0 "$PID" 2>/dev/null; then
        echo "[$(date '+%Y-%m-%d %H:%M:%S')] Skipped: previous run (PID $PID) still active" >> "$LOG_FILE"
        exit 0
    fi
    rm -f "$LOCK_FILE"
fi
echo $$ > "$LOCK_FILE"
trap 'rm -f "$LOCK_FILE"' EXIT

cd "$PROJECT_PATH" || exit 1

# Log run start
echo "" >> "$LOG_FILE"
echo "---" >> "$LOG_FILE"
echo "## Run: $(date '+%Y-%m-%d %H:%M:%S')" >> "$LOG_FILE"
echo "" >> "$LOG_FILE"

# Run Claude headless — acceptEdits + explicit tool allowlist avoids interactive prompts
claude -p "Proceed with qa-audit" \
  --model opus \
  --permission-mode acceptEdits \
  --allowedTools "Read,Write,Edit,Glob,Grep,Bash(git:*),Bash(uv:*),Bash(uvx:*),Bash(pytest:*),mcp__notebooklm__*" 2>&1 | tee -a "$LOG_FILE"

echo "Completed at: $(date '+%Y-%m-%d %H:%M:%S')" >> "$LOG_FILE"
